### ISSUE TITLE
Change from homemaker?

### ISSUE THREAD

**Issue by RickCogley** [andrewrynhard/dotfiles#1]
Hi Andrew, I was looking into homemaker, and noticed your PR in there, regarding a cleaner cli and encryption. I wanted to see if you had made any progress locally, and it appears you've switched to or have written (?) alterant. 

Just wondering if you could shed some light on the status? I'm just now looking for a solution for dot file management, so I thought I would give you a shout and ask. 

Thanks
Rick

**Comment by andrewrynhard** [comment]
@RickCogley Hello. Yes I have written my own dot file manager. I work on it in my spare time but it is still usable. The `master` branch works fine but I would recommend using the `develop` branch. It supports OpenPGP encryption. You can generate the keys (stored at ~/.alterant) and then encrypt/decrypt with them. If you look at my dotfiles repo you will see a `macbookpro` branch that utilizes the latest `alterant` version. At this point the only thing about the `develop` branch of `alterant` is that once your dotfiles repo is cloned (this is done automatically by alterant using `git2go`) the branch is currently checked out and is detached. Committing changes becomes cumbersome. You would have to clone the repo somewhere, make the changes, push the changes, and then run `alterant` again. If you would like, you could create an issue for `alternate` that I can use to explain how to use the `develop` branch.
